language: node_js
node_js:
  - "node"
  - "8"
install: npm ci
script: npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
  local-dir: output